basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'
urlpatterns = [
    path('', views.register_page, name="register"),
]

encryption/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include('basic_app.urls'), name="register"),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.user_special, name='special'),
    path('', views.index, name="index"),
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class User_Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # additional fields

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import User_Profile

def email_validator(value):
    current_email = [i.email for i in User.objects.all()]
    if value in current_email:
        raise forms.ValidationError("This email already exists")

class Userform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField(validators=[email_validator])
    class Meta():
        model = User
        fields = ('first_name','last_name','email','username','password')

class UserProfileForm(forms.ModelForm):
    class Meta():
        model = User_Profile
        fields = ('portfolio_site','profile_pic')

basic_app/views.py
from django.shortcuts import render
from basic_app.forms import Userform, UserProfileForm
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django import forms

# Create your views here.
def index(request, registered=False, comments=''):
    return render(request, 'html/index.html', context={'registered':registered, 'comments':comments})

def register_page(request):
    user_form = Userform()
    profile_form = UserProfileForm()
    if request.method == "POST":
        user_form = Userform(request.POST)
        profile_form = UserProfileForm(request.POST, request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            return index(request, True)
        else:
            print(user_form.errors, profile_form.errors)

    return render(request, 'html/register.html', context={'user_form':user_form, 
                                                            'profile_form':profile_form,})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            print('Someone tried to login and failed')
            print('username: {} and password: {}'.format(username, password))
            return index(request, False, 'Invalid login details supplied \n Please try to login again')
    else:
        return render(request, 'html/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def user_special(request):
    return HttpResponse('You are logged in. Nice!')

templates/html/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static  "css/bootstrap.css" %}">
    <script type="text/javascript" src="{% static "js/jquery.js" %}"></script>
    <title>Home Page</title>
</head>
<body>
    <div class="container">

        <!-- This is the Navbar  -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Django</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url "basic_app:register" %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                {% if  user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
            </div>
        </nav>


        <!-- Calling a Jumbotron  -->
        <div class="jumbotron">
            {% block body_block %}
            {% if not registered %}
                <h1 class="display-4">Welcome to Django level 5</h1>
                <p class="lead">If you haven't registered yet, go ahead and register!</p>
            {% else %}
                <h1 class="display-4">Thanks for registration!</h1>
                <p class="lead">Please select the register tab if you want to register another user!</p>
            {% endif %}
            <h2>{{ comments }}</h2>
            {% endblock %}
          </div>



    </div>
</body>
<script type="text/javascript" src="{% static "js/bootstrap.js" %}"></script>
</html>

templates/html/login.html
<!DOCTYPE html>
{% extends 'html/index.html' %}
{% block body_block %}
<h2>This is the login page!</h2>
    <form action="{% url 'login' %}" method="POST">
        {% csrf_token %}
        <p><label for="username">Username</label>
        <input type="text" name="username" placeholder="Enter Username"></p>
        <p><label for="password">Password</label>
        <input type="password" name="password" placeholder="Enter your password"></p>
        <p><input type="submit" class="button btn-primary" value="Login" name="submit"></p>
    </form>
{% endblock %}

templates/html/register.html
<!DOCTYPE html>
{% extends 'html/index.html' %}
{% block body_block %}
    <h1>Please fill out this form to register:</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input class='button btn-large btn-primary' type="submit" value="submit">
    </form>
{% endblock %}